apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: k8s-web-to-nginx
  
  template:
    metadata:
      labels:
        app: k8s-web-to-nginx
    
    spec:
      containers:
      - name: k8s-web-to-nginx
  
        image: gitbaburin/k8s-web-to-nginx-hu:1.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000


--- 
apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-nginx
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-to-nginx
  ports:
  - port: 3000
    targetPort: 3000

